spring.application.name=app-tasks
api.version=1.0

spring.datasource.url=jdbc:postgresql://localhost:5432/Tasks
spring.datasource.username=Marcos
spring.datasource.password=Marqos12
# MyBatis settings
#mybatis.type-aliases-package=com.tasks.model
#mybatis.mapper-locations=classpath:mybatis/mappers/*.xml


